import { STORES } from './gwaaDB';

export const DEFAULTS: Record<string, object[]> = {
  [STORES.ACTIVITY]: [
    { order: 1, imageData: null, tag: 'EDUCATION', tagColor: 'green', icon: '🎓',
      title: '반려동물 교육',
      desc: '독스포츠(어질리티), 오비디언스 교육부터 반려동물행동지도사 국가자격증 취득까지. 전문 트레이너와 체계적인 커리큘럼.',
      link: '/education', linkText: '교육 신청하기 →' },
    { order: 2, imageData: null, tag: 'EVENTS', tagColor: 'blue', icon: '🎪',
      title: '반려동물 행사',
      desc: '강원도 전역에서 펼쳐지는 반려동물 문화축제, 트레킹, 캠핑, 사진공모전. 2021년부터 4만명이 함께했습니다.',
      link: '/events', linkText: '행사 보기 →' },
    { order: 3, imageData: null, tag: 'MATESHIP', tagColor: 'amber', icon: '🤝',
      title: '메이트쉽 멤버십',
      desc: '호텔, 카페, 캠핑, 사료·용품 할인과 행사 우선 참여까지. 메이트쉽 회원은 연간 40만원 이상 절약합니다.',
      link: '/mateship', linkText: '혜택 보기 →' },
  ],
  [STORES.EVENT]: [
    { order: 1, imageData: null, images: [], title: '2026 반려동물 숲치유 in 양평',
      date: '2026.04.04 — 2026.11.07', loc: '숲치유 · 양평',
      desc: '반려동물과 함께하는 자연 속 힐링 프로그램. 전문 숲치유사와 함께 진행됩니다.',
      content: '', status: 'live', link: '',
      benefit: '⭐ 메이트쉽 회원 우선 예약', ctaText: '사전 예약하기 →' },
    { order: 2, imageData: null, images: [], title: '2026 반려동물 캠핑 프로그램',
      date: '2026.05.01 — 2026.09.30', loc: '캠핑 · 강원도',
      desc: '강원도 야외 캠핑장에서 반려동물과 함께하는 1박 2일 캠핑. 메이트쉽 회원 우선 신청.',
      content: '', status: 'soon', link: '',
      benefit: '⭐ 회원 30% 할인', ctaText: '사전 신청하기 →' },
    { order: 3, imageData: null, images: [], title: '반려동물 동반 요가 클래스',
      date: '2026.03.01 — 2026.12.31', loc: '요가 · 원주',
      desc: '반려견과 함께 즐기는 요가 클래스. 매월 정기 운영. 메이트쉽 회원 무료.',
      content: '', status: 'live', link: '',
      benefit: '⭐ 회원 무료 이용', ctaText: '신청하기 →' },
  ],
  [STORES.LOOKBOOK]: [
    { order: 1, imageData: null, label: '캠핑 · 아웃도어', link: '/travel',    isMain: true  },
    { order: 2, imageData: null, label: '트레킹',          link: '/travel',    isMain: false },
    { order: 3, imageData: null, label: '문화축제',        link: '/travel',    isMain: false },
    { order: 4, imageData: null, label: '교육',            link: '/education', isMain: false },
    { order: 5, imageData: null, label: '봉사활동',        link: '/about',     isMain: false },
  ],
  [STORES.ARCHIVE]: [
    { order: 1, feat: true, year: 2025, title: 'Mission Dog Trekking — 고성',
      loc: '고성', ppl: '300+', date: '2025.10.18(토) 13:00 ~ 18:00',
      place: '강원특별자치도 고성군 현내면 일대', part: '자체 기획·제작·운영',
      desc: '강원도 고성에서 사람과 반려견이 함께 자연을 걷고 교감하는 트레킹 이벤트.',
      imageData: null, imageData2: null },
    { order: 2, feat: false, year: 2025, title: '가평군 반려동물 문화행사',
      loc: '가평', ppl: '5,000', date: '2025.06.07(토) 10:00 ~ 17:00',
      place: '경기도 가평군 자라섬 중도 일원', part: '자체 기획·제작·운영',
      desc: '반려동물과 함께하는 야외 문화축제. 5,000여 명의 반려인이 참가했습니다.',
      imageData: null, imageData2: null },
    { order: 3, feat: false, year: 2024, title: '제2회 원주시 반려동물문화행사',
      loc: '원주', ppl: '5,000', date: '2024.10.19(토)',
      place: '강원특별자치도 원주시 중앙공원', part: '자체 기획·제작·운영',
      desc: '원주시 반려인들을 위한 반려동물 문화행사 2회. 5,000여 명이 참가했습니다.',
      imageData: null, imageData2: null },
    { order: 4, feat: true, year: 2024, title: '제2회 강릉시반려동물문화축제',
      loc: '강릉', ppl: '3,500', date: '2024.09.28(토)',
      place: '강원특별자치도 강릉시 경포호 일원', part: '자체 기획·제작·운영',
      desc: '강릉 경포호 일대에서 열린 반려동물 문화축제. 3,500명이 참가했습니다.',
      imageData: null, imageData2: null },
    { order: 5, feat: false, year: 2024, title: '삼척해안 반려견 트레킹 & 페스타',
      loc: '삼척', ppl: '2,000', date: '2024 (2회 진행)',
      place: '강원특별자치도 삼척시 해안일대', part: '자체 기획·제작·운영',
      desc: '삼척 해안을 따라 반려견과 함께 걷는 트레킹 행사. 총 2,000여 명이 참가했습니다.',
      imageData: null, imageData2: null },
    { order: 6, feat: false, year: 2024, title: '원주시 반려견 이동식 운동장',
      loc: '원주', ppl: '2,190', date: '2024 (7회 진행)',
      place: '강원특별자치도 원주시 일원', part: '자체 기획·제작·운영',
      desc: '원주시와 협력하여 운영한 반려견 이동식 운동장. 7회에 걸쳐 진행되었습니다.',
      imageData: null, imageData2: null },
    { order: 7, feat: false, year: 2023, title: '제1회 강릉시반려동물문화축제',
      loc: '강릉', ppl: '3,000', date: '2023.09.23(토)',
      place: '강원특별자치도 강릉시 경포호 일원', part: '자체 기획·제작·운영',
      desc: '강릉시와 함께한 첫 번째 반려동물 문화축제. 3,000여 명의 반려인이 참가했습니다.',
      imageData: null, imageData2: null },
    { order: 8, feat: false, year: 2022, title: '전국댕댕자랑 사진공모전',
      loc: '원주', ppl: '1,340', date: '2022',
      place: '강원특별자치도 원주시 (온·오프라인)', part: '자체 기획·제작·운영',
      desc: '전국 반려인을 대상으로 진행한 반려동물 사진공모전. 1,340명이 참여했습니다.',
      imageData: null, imageData2: null },
    { order: 9, feat: false, year: 2021, title: '제1회 강원도반려동물문화축제',
      loc: '원주', ppl: '1,500', date: '2021 — 협회 창립',
      place: '강원특별자치도 원주시', part: '자체 기획·제작·운영',
      desc: '협회 창립과 함께 열린 제1회 반려동물문화축제. 1,500명이 참가했습니다.',
      imageData: null, imageData2: null },
  ],
  [STORES.PLACES]: [
    { order: 1,  region: '춘천', type: '관광', typeLabel: '관광지',    name: '삼악산 호수 케이블카',    icon: '🚡', address: '춘천시 서면 박사로 473',              feature: '소양강 호수 위 케이블카', desc: '소양강 호수 위 케이블카. 반려동물 전용 캐빈 운영.', petInfo: '🐾 소형 반려동물 · 케이지 또는 가방 필수', isPartner: false, imageData: null, mapUrl: 'https://map.kakao.com', hours: '09:00–18:00 (연중무휴)', price: '왕복 성인 14,000원' },
    { order: 2,  region: '춘천', type: '카페', typeLabel: '카페',      name: '라붐 애견 동반 카페',     icon: '☕', address: '춘천시 효자동 충열로 78',             feature: '메이트쉽 회원 30% 할인',  desc: '춘천 인기 반려견 동반 카페. 야외 공간 보유.', petInfo: '🐾 소형견 우선 · 중형견 사전 문의', isPartner: true,  imageData: null, mapUrl: 'https://map.kakao.com', hours: '10:00–21:00 (연중무휴)', price: '음료 6,000원~' },
    { order: 3,  region: '원주', type: '카페', typeLabel: '카페',      name: '퍼피파크 애견카페',       icon: '🐶', address: '원주시 단구동 반곡로 45',             feature: '메이트쉽 회원 30% 할인',  desc: '원주 대표 애견카페. 실내외 놀이 공간 완비.', petInfo: '🐾 접종 완료견만 입장 가능', isPartner: true,  imageData: null, mapUrl: 'https://map.kakao.com', hours: '10:00–20:00 (화요일 휴무)', price: '입장료 5,000원 (음료 포함)' },
    { order: 4,  region: '원주', type: '공원', typeLabel: '공원·산책', name: '치악산 반려견 등산로',    icon: '🏔️', address: '원주시 소초면 치악로 684',            feature: '무료 (황골 코스 허용)', desc: '국립공원 내 반려견 허용 등산로. 황골~비로봉 왕복 약 6km.', petInfo: '🐾 목줄 착용 필수 · 배변봉투 지참', isPartner: false, imageData: null, mapUrl: 'https://map.kakao.com', hours: '일출~일몰 (계절별 상이)', price: '무료' },
    { order: 5,  region: '원주', type: '공원', typeLabel: '산책',      name: '원주 섬강 반려견 산책로',  icon: '🌊', address: '원주시 섬강변 일대',                  feature: '무료', desc: '강변 따라 걷는 반려견 산책 코스. 왕복 약 4km.', petInfo: '🐾 목줄 착용 필수', isPartner: false, imageData: null, mapUrl: 'https://map.kakao.com', hours: '24시간 개방', price: '무료' },
    { order: 6,  region: '강릉', type: '호텔', typeLabel: '호텔',      name: '세인트존스호텔',          icon: '🏨', address: '강릉시 강문동 34-2',                  feature: '인터넷 최저가 이하 특가', desc: '경포 해변 5성급 호텔. 반려동물 동반 객실 운영. 해변까지 도보 2분.', petInfo: '🐾 소형견(7kg↓) · 케이지 필수', isPartner: true,  imageData: null, mapUrl: 'https://map.kakao.com', hours: '체크인 15:00 / 체크아웃 11:00', price: '1박 150,000원~ (반려동물 추가 요금 30,000원)' },
    { order: 7,  region: '강릉', type: '카페', typeLabel: '카페',      name: '도그비치 카페',           icon: '☕', address: '강릉시 안현동 해변로 123',            feature: '해변 바로 앞 · 야외 테라스', desc: '강릉 해변가 반려견 동반 카페. 야외 테라스에서 바다 전망.', petInfo: '🐾 전 견종 · 외부 음식 반입 불가', isPartner: false, imageData: null, mapUrl: 'https://map.kakao.com', hours: '09:00–21:00 (연중무휴)', price: '음료 7,000원~' },
    { order: 8,  region: '강릉', type: '공원', typeLabel: '해변·산책', name: '사천 해변 반려견 산책로',  icon: '🌊', address: '강릉시 사천면 해안로',                feature: '무료 · 연중 개방', desc: '강릉 바다를 보며 산책. 해안선 따라 왕복 약 3km.', petInfo: '🐾 목줄 착용 필수 · 성수기 일부 제한', isPartner: false, imageData: null, mapUrl: 'https://map.kakao.com', hours: '24시간 개방 (성수기 시간 제한 있음)', price: '무료' },
    { order: 9,  region: '속초', type: '공원', typeLabel: '해변',      name: '속초 반려견 해수욕장',    icon: '🌊', address: '속초시 대포동 해수욕장길',            feature: '7~8월 시즌 운영', desc: '강원도 유일 반려견 전용 해수욕장 구역. 여름 시즌 한정 운영.', petInfo: '🐾 목줄 착용 필수 · 배변봉투 지참', isPartner: false, imageData: null, mapUrl: 'https://map.kakao.com', hours: '7월~8월 10:00–18:00', price: '무료' },
    { order: 10, region: '양양', type: '캠핑', typeLabel: '캠핑',      name: '죽도해변 반려견 캠핑장',  icon: '⛺', address: '양양군 현남면 죽도해변길 80',         feature: '메이트쉽 회원 30% 할인', desc: '해변 바로 앞 캠핑장. 전 사이트 반려견 동반 가능.', petInfo: '🐾 전 견종 · 목줄 상시 착용', isPartner: true,  imageData: null, mapUrl: 'https://map.kakao.com', hours: '체크인 14:00 / 체크아웃 11:00', price: '1박 40,000원~ (회원 28,000원~)' },
    { order: 11, region: '고성', type: '공원', typeLabel: '트레킹',    name: '건봉사 반려견 산책로',    icon: '🏔️', address: '고성군 거진읍 건봉사로 723',          feature: '천년 고찰 주변 청정 자연', desc: '천년 고찰 주변 청정 자연 트레킹 코스. 왕복 약 5km.', petInfo: '🐾 목줄 착용 필수', isPartner: false, imageData: null, mapUrl: 'https://map.kakao.com', hours: '07:00–18:00 (연중무휴)', price: '무료' },
    { order: 12, region: '평창', type: '호텔', typeLabel: '리조트',    name: '피닉스파크 리조트',       icon: '🏔️', address: '평창군 봉평면 태기로 174',            feature: '메이트쉽 회원 할인', desc: '사계절 리조트. 반려동물 동반 펜션동 운영. 여름·겨울 시즌 인기.', petInfo: '🐾 반려견 전 견종 · 목줄 착용 필수', isPartner: true,  imageData: null, mapUrl: 'https://map.kakao.com', hours: '체크인 15:00 / 체크아웃 11:00', price: '1박 120,000원~ (회원 할인 적용 시)' },
    { order: 13, region: '평창', type: '관광', typeLabel: '관광지',    name: '하늘목장',                icon: '🐄', address: '평창군 대관령면 꽃밭양지길 458-23', feature: '대관령 목장', desc: '해발 1,080m 대관령 목장. 반려견 동반 가능 구역 지정.', petInfo: '🐾 목줄 착용 필수 · 가축 구역 접근 금지', isPartner: false, imageData: null, mapUrl: 'https://map.kakao.com', hours: '09:00–18:00 (연중무휴)', price: '성인 10,000원 / 반려동물 무료' },
    { order: 14, region: '홍천', type: '관광', typeLabel: '테마파크',  name: '반려동물 테마파크',       icon: '🎡', address: '홍천군 북방면 홍천로 956',            feature: '어질리티 체험 · 수영장', desc: '어질리티 체험, 수영장, 포토존 완비. 반려동물 전용 파크.', petInfo: '🐾 전 견종 · 접종 증명서 필수', isPartner: true,  imageData: null, mapUrl: 'https://map.kakao.com', hours: '10:00–18:00 (월요일 휴무)', price: '입장료 15,000원 (반려동물 포함)' },
    { order: 15, region: '인제', type: '관광', typeLabel: '액티비티',  name: '내린천 반려견 래프팅',    icon: '🌊', address: '인제군 기린면 내린천로 2011',         feature: '메이트쉽 회원 할인', desc: '반려견과 래프팅. 안전 조끼 대여 제공. 약 2시간 코스.', petInfo: '🐾 중형견 이하 · 안전 조끼 착용 필수', isPartner: true,  imageData: null, mapUrl: 'https://map.kakao.com', hours: '09:00–17:00 (4월~10월 운영)', price: '1인 35,000원 (회원 할인 적용 시)' },
    { order: 16, region: '정선', type: '관광', typeLabel: '관광지',    name: '정선 레일바이크',         icon: '🚂', address: '정선군 여량면 레일바이크길 230',      feature: '구절리~아우라지 구간', desc: '반려동물 동반 탑승 가능한 레일바이크. 약 7.2km 코스.', petInfo: '🐾 소형 반려동물 · 케이지 필수', isPartner: false, imageData: null, mapUrl: 'https://map.kakao.com', hours: '09:00–17:30 (연중무휴)', price: '2인승 35,000원 / 4인승 50,000원' },
    { order: 17, region: '삼척', type: '관광', typeLabel: '관광지',    name: '삼척 해상 케이블카',      icon: '🌊', address: '삼척시 정상동 이사부길 33',           feature: '동해 바다 위 케이블카', desc: '동해 바다 위 케이블카. 케이지 대여 가능. 동양 최장 구간.', petInfo: '🐾 소형 반려동물 케이지 탑승 가능', isPartner: false, imageData: null, mapUrl: 'https://map.kakao.com', hours: '09:00–18:00 (연중무휴)', price: '왕복 성인 12,000원 (케이지 대여 2,000원)' },
    { order: 18, region: '양평', type: '공원', typeLabel: '공원·산책', name: '두물머리 반려견 산책',    icon: '🌿', address: '양평군 양서면 양수리',               feature: '무료 · 연중 개방', desc: '한강 두물머리 산책. 반려견 동반 가능. 매화·유채꽃 시즌 인기.', petInfo: '🐾 목줄 착용 필수', isPartner: false, imageData: null, mapUrl: 'https://map.kakao.com', hours: '24시간 개방', price: '무료' },
  ],
  [STORES.GALLERY]: [
    { order: 1, imageData: null, caption: '2025 Mission Dog Trekking — 고성', active: true },
    { order: 2, imageData: null, caption: '가평군 반려동물 문화행사', active: true },
    { order: 3, imageData: null, caption: '강원도 반려동물 캠핑 페스티벌', active: true },
    { order: 4, imageData: null, caption: '어질리티 챔피언십 대회', active: true },
    { order: 5, imageData: null, caption: '반려견 트레킹 & 해변 페스타', active: true },
  ],
  [STORES.MATESHIP]: [
    { order: 1, name: '세인트존스호텔',         region: '강릉', type: '호텔',     discount: '인터넷 최저가 이하', icon: '🏨',  gradient: 'linear-gradient(135deg,#dbeafe 0%,#93c5fd 100%)', link: '#', imageData: null },
    { order: 2, name: '피닉스파크 리조트',      region: '평창', type: '리조트',   discount: '회원 할인',          icon: '⛷️',  gradient: 'linear-gradient(135deg,#cffafe 0%,#67e8f9 100%)', link: '#', imageData: null },
    { order: 3, name: '퍼피파크 애견카페',      region: '원주', type: '카페',     discount: '30% 할인',           icon: '☕',  gradient: 'linear-gradient(135deg,#fef3c7 0%,#fcd34d 100%)', link: '#', imageData: null },
    { order: 4, name: '죽도해변 반려견 캠핑장', region: '양양', type: '캠핑',     discount: '30% 할인',           icon: '🏕️', gradient: 'linear-gradient(135deg,#dcfce7 0%,#86efac 100%)', link: '#', imageData: null },
    { order: 5, name: '반려동물 테마파크',      region: '홍천', type: '공원',     discount: '회원 할인',          icon: '🌳',  gradient: 'linear-gradient(135deg,#d1fae5 0%,#6ee7b7 100%)', link: '#', imageData: null },
    { order: 6, name: '내린천 반려견 래프팅',   region: '인제', type: '액티비티', discount: '회원 할인',          icon: '🚣',  gradient: 'linear-gradient(135deg,#dbeafe 0%,#7dd3fc 100%)', link: '#', imageData: null },
  ],
};

export const DEFAULT_HASHTAGS = [
  { page: 'index',     tags: ['#강원도반려동물협회', '#강원도반려동물', '#메이트쉽멤버십', '#독스포츠교육', '#어질리티교육', '#오비디언스훈련', '#반려동물행동지도사', '#강원도반려견여행', '#원주반려동물', '#강릉반려동물'] },
  { page: 'events',    tags: ['#강원도반려동물행사', '#반려동물축제', '#반려견트레킹', '#반려동물캠핑', '#강원도반려견문화', '#GWAA행사'] },
  { page: 'travel',    tags: ['#강원도반려동물여행', '#강원도반려견동반', '#강릉반려동물카페', '#속초반려견해변', '#평창반려동물리조트', '#강원도반려견캠핑'] },
  { page: 'education', tags: ['#강원도반려동물교육', '#어질리티클럽원주', '#어질리티교육', '#오비디언스훈련', '#반려동물행동지도사', '#독스포츠강원도', '#국가자격증반려동물'] },
  { page: 'mateship',  tags: ['#메이트쉽멤버십', '#반려동물할인', '#강원도제휴업체', '#반려동물여행할인', '#GWAA회원'] },
  { page: 'about',     tags: ['#강원도반려동물협회', '#GWAA', '#반려동물문화', '#강원도반려인', '#사단법인협회'] },
];
