import { STORES } from './stores';

export const DEFAULTS: Record<string, object[]> = {
  [STORES.ACTIVITY]: [
    { order: 1, imageData: null, tag: 'EDUCATION', tagColor: 'green', icon: '🎓',
      title: '반려동물 교육',
      desc: '독스포츠(어질리티), 오비디언스 교육부터 반려동물행동지도사 국가자격증 취득까지. 전문 트레이너와 체계적인 커리큘럼.',
      link: '/education', linkText: '교육 신청하기 →' },
    { order: 2, imageData: null, tag: 'EVENTS', tagColor: 'blue', icon: '🎪',
      title: '반려동물 행사',
      desc: '강원도 전역에서 펼쳐지는 반려동물 문화축제, 트레킹, 캠핑, 사진공모전. 2021년부터 4만명이 함께했습니다.',
      link: '/events', linkText: '행사 보기 →' },
    { order: 3, imageData: null, tag: 'MATESHIP', tagColor: 'amber', icon: '🤝',
      title: '메이트쉽 멤버십',
      desc: '호텔, 카페, 캠핑, 사료·용품 할인과 행사 우선 참여까지. 메이트쉽 회원은 연간 40만원 이상 절약합니다.',
      link: '/mateship', linkText: '혜택 보기 →' },
  ],
  [STORES.EVENT]: [
    { order: 1, imageData: null, images: [], title: '2026 반려동물 숲치유 in 양평',
      date: '2026.04.04 — 2026.11.07', loc: '숲치유 · 양평',
      desc: '반려동물과 함께하는 자연 속 힐링 프로그램. 전문 숲치유사와 함께 진행됩니다.',
      content: '', status: 'live', link: '',
      benefit: '⭐ 메이트쉽 회원 우선 예약', ctaText: '사전 예약하기 →' },
    { order: 2, imageData: null, images: [], title: '2026 반려동물 캠핑 프로그램',
      date: '2026.05.01 — 2026.09.30', loc: '캠핑 · 강원도',
      desc: '강원도 야외 캠핑장에서 반려동물과 함께하는 1박 2일 캠핑. 메이트쉽 회원 우선 신청.',
      content: '', status: 'soon', link: '',
      benefit: '⭐ 회원 30% 할인', ctaText: '사전 신청하기 →' },
    { order: 3, imageData: null, images: [], title: '반려동물 동반 요가 클래스',
      date: '2026.03.01 — 2026.12.31', loc: '요가 · 원주',
      desc: '반려견과 함께 즐기는 요가 클래스. 매월 정기 운영. 메이트쉽 회원 무료.',
      content: '', status: 'live', link: '',
      benefit: '⭐ 회원 무료 이용', ctaText: '신청하기 →' },
  ],
  [STORES.LOOKBOOK]: [
    { order: 1, imageData: null, label: '캠핑 · 아웃도어', link: '/travel',    isMain: true  },
    { order: 2, imageData: null, label: '트레킹',          link: '/travel',    isMain: false },
    { order: 3, imageData: null, label: '문화축제',        link: '/travel',    isMain: false },
    { order: 4, imageData: null, label: '교육',            link: '/education', isMain: false },
    { order: 5, imageData: null, label: '봉사활동',        link: '/about',     isMain: false },
  ],
  [STORES.ARCHIVE]: [
    { order: 1, feat: true, year: 2025, title: '제3회 원주시 반려동물문화축제 — 애니멀대학교',
      loc: '원주', ppl: '6,000', date: '2025.10.04(토)',
      place: '강원특별자치도 원주시 중앙공원', part: '자체 기획·제작·운영', organizer: '원주시·강원도반려동물협회',
      desc: '6,000명이 한 번에 대학교가 됐습니다. 원주 중앙공원이 체육관·예술관·강의실로 가득 찬 날이었습니다.',
      imageData: '/images/events/wonju-2025/01.webp',
      imageData2: '/images/events/wonju-2025/02.webp',
      images: ['/images/events/wonju-2025/01.webp', '/images/events/wonju-2025/02.webp', '/images/events/wonju-2025/03.webp', '/images/events/wonju-2025/04.webp'] },
    { order: 2, feat: false, year: 2025, title: 'Mission Dog Trekking — 고성',
      loc: '고성', ppl: '300+', date: '2025.10.18(토) 13:00 ~ 18:00',
      place: '강원특별자치도 고성군 현내면 일대', part: '자체 기획·제작·운영', organizer: '강원도반려동물협회',
      desc: '함께 길 위에 섰습니다. 고성의 바다와 숲 사이로, 반려견과 보호자가 어깨를 나란히 걸었습니다.',
      imageData: '/images/events/gosung-trek-2025/01.webp',
      imageData2: '/images/events/gosung-trek-2025/02.webp',
      images: ['/images/events/gosung-trek-2025/01.webp', '/images/events/gosung-trek-2025/02.webp', '/images/events/gosung-trek-2025/03.webp', '/images/events/gosung-trek-2025/04.webp', '/images/events/gosung-trek-2025/poster.webp'] },
    { order: 3, feat: false, year: 2025, title: '고성 해변 반려견 축제 — 썬베드비치',
      loc: '고성', ppl: '1,000+', date: '2025.08',
      place: '강원특별자치도 고성군 해변 일원', part: '자체 기획·제작·운영', organizer: '강원도반려동물협회',
      desc: '파도 앞에서, 반려견도 여름을 누렸습니다. 고성 해변이 하루 동안 반려견의 천국이 됐습니다.',
      imageData: '/images/events/beach-gosung-2025/01.webp',
      imageData2: '/images/events/beach-gosung-2025/02.webp',
      images: ['/images/events/beach-gosung-2025/01.webp', '/images/events/beach-gosung-2025/02.webp', '/images/events/beach-gosung-2025/03.webp', '/images/events/beach-gosung-2025/04.webp', '/images/events/beach-gosung-2025/05.webp'] },
    { order: 4, feat: false, year: 2025, title: '댕댕방범대 프로그램',
      loc: '원주', ppl: '', date: '2025.06',
      place: '강원특별자치도 원주시 일원', part: '자체 기획·제작·운영', organizer: '강원도반려동물협회',
      desc: '우리동네는 내가 지킨다 — 반려견과 함께. 방범과 산책을, 지역과 반려인을 하나로 연결한 프로젝트.',
      imageData: '/images/events/dangdang-2025/01.webp',
      imageData2: '/images/events/dangdang-2025/02.webp',
      images: ['/images/events/dangdang-2025/01.webp', '/images/events/dangdang-2025/02.webp', '/images/events/dangdang-2025/03.webp', '/images/events/dangdang-2025/04.webp', '/images/events/dangdang-2025/05.webp', '/images/events/dangdang-2025/06.webp', '/images/events/dangdang-2025/07.webp', '/images/events/dangdang-2025/08.webp', '/images/events/dangdang-2025/09.webp', '/images/events/dangdang-2025/10.webp'] },
    { order: 5, feat: false, year: 2025, title: '가평군 반려동물 문화행사 — 활짝펫',
      loc: '가평', ppl: '5,000', date: '2025.06.07(토) 10:00 ~ 17:00',
      place: '경기도 가평군 자라섬 중도 일원', part: '자체 기획·제작·운영', organizer: '가평군·강원도반려동물협회',
      desc: '꽃이 피듯, 웃음도 폈습니다. 자라섬에 5,000명이 모여 반려동물과 함께 봄을 맞았습니다.',
      imageData: '/images/events/gapyeong-2025/01.webp',
      imageData2: '/images/events/gapyeong-2025/02.webp',
      images: ['/images/events/gapyeong-2025/01.webp', '/images/events/gapyeong-2025/02.webp', '/images/events/gapyeong-2025/03.webp'] },
    { order: 6, feat: false, year: 2025, title: '반려동물 산책 교육 프로그램',
      loc: '원주', ppl: '', date: '2025',
      place: '강원특별자치도 원주시 일원', part: '자체 기획·제작·운영', organizer: '강원도반려동물협회',
      desc: '올바른 산책은 관계에서 시작됩니다. 리드줄 하나로, 반려견과 보호자 사이의 거리가 가까워졌습니다.',
      imageData: '/images/events/walk-edu-2025/01.webp',
      imageData2: '/images/events/walk-edu-2025/02.webp',
      images: ['/images/events/walk-edu-2025/01.webp', '/images/events/walk-edu-2025/02.webp', '/images/events/walk-edu-2025/03.webp', '/images/events/walk-edu-2025/04.webp', '/images/events/walk-edu-2025/05.webp', '/images/events/walk-edu-2025/06.webp', '/images/events/walk-edu-2025/07.webp', '/images/events/walk-edu-2025/08.webp', '/images/events/walk-edu-2025/09.webp', '/images/events/walk-edu-2025/10.webp', '/images/events/walk-edu-2025/11.webp', '/images/events/walk-edu-2025/12.webp'] },
    { order: 7, feat: false, year: 2025, title: '제3회 강릉시반려동물문화축제 — 올림펫',
      loc: '강릉', ppl: '3,500', date: '2025.10.18(토) ~ 19(일)',
      place: '강원특별자치도 강릉시 일원', part: '자체 기획·제작·운영', organizer: '강릉시·강원도반려동물협회',
      desc: '경포에 3,500개의 발소리가 울려 퍼진 날. 강릉이 다시, 반려동물의 도시가 됐습니다.',
      imageData: '/images/events/gangreung-2025/01.webp',
      imageData2: '/images/events/gangreung-2025/poster.webp',
      images: ['/images/events/gangreung-2025/01.webp', '/images/events/gangreung-2025/poster.webp'] },
    { order: 8, feat: false, year: 2024, title: '제2회 원주시 반려동물문화행사 — 펫밀리',
      loc: '원주', ppl: '5,000', date: '2024.10.19(토)',
      place: '강원특별자치도 원주시 중앙공원', part: '자체 기획·제작·운영', organizer: '원주시·강원도반려동물협회',
      desc: '5,000명이 다시 원주 중앙공원에 모인 날. 두 번째 만남, 더 커진 설렘이었습니다.',
      imageData: '/images/events/wonju-2024/10.webp',
      imageData2: '/images/events/wonju-2024/11.webp',
      images: ['/images/events/wonju-2024/10.webp', '/images/events/wonju-2024/11.webp', '/images/events/wonju-2024/12.webp', '/images/events/wonju-2024/13.webp', '/images/events/wonju-2024/14.webp', '/images/events/wonju-2024/01.webp', '/images/events/wonju-2024/02.webp', '/images/events/wonju-2024/03.webp', '/images/events/wonju-2024/04.webp', '/images/events/wonju-2024/05.webp', '/images/events/wonju-2024/07.webp', '/images/events/wonju-2024/08.webp', '/images/events/wonju-2024/09.webp', '/images/events/wonju-2024/poster.webp'] },
    { order: 9, feat: false, year: 2024, title: '원주시 반려동물 교육 프로그램',
      loc: '원주', ppl: '', date: '2024',
      place: '강원특별자치도 원주시 일원', part: '자체 기획·제작·운영', organizer: '강원도반려동물협회',
      desc: '반려견과 눈을 맞추고, 함께 달렸습니다. 어질리티와 오비디언스 — 기술이 아닌 신뢰를 쌓는 시간이었습니다.',
      imageData: '/images/events/edu-2024/01.webp',
      imageData2: '/images/events/edu-2024/02.webp',
      images: ['/images/events/edu-2024/01.webp', '/images/events/edu-2024/02.webp', '/images/events/edu-2024/03.webp'] },
    { order: 10, feat: false, year: 2024, title: '제2회 강릉시반려동물문화축제',
      loc: '강릉', ppl: '3,500', date: '2024.10.19(토)',
      place: '강원특별자치도 강릉종합운동장 야외공연장', part: '자체 기획·제작·운영', organizer: '강릉시·강원도반려동물협회',
      desc: '경포호에 3,500개의 발소리가 울렸습니다. 두 해 연속 강릉을, 반려동물이 수놓았습니다.',
      imageData: '/images/events/olimpet-2024/poster.webp',
      imageData2: '/images/events/olimpet-2024/poster2.webp',
      images: ['/images/events/olimpet-2024/poster.webp', '/images/events/olimpet-2024/poster2.webp', '/images/events/olimpet-2024/poster3.webp', '/images/events/olimpet-2024/poster4.webp'] },
    { order: 11, feat: false, year: 2024, title: '삼척해안 반려견 트레킹 & 페스타',
      loc: '삼척', ppl: '2,000', date: '2024 (2회 진행)',
      place: '강원특별자치도 삼척시 해안일대', part: '자체 기획·제작·운영', organizer: '강원도반려동물협회',
      desc: '삼척 해안을 반려견과 함께 걸었습니다. 파도 소리와 발소리가 함께한 2,000명의 기억.',
      imageData: '/images/events/samcheok-trek-2024/01.webp',
      imageData2: '/images/events/samcheok-trek-2024/poster.webp',
      images: ['/images/events/samcheok-trek-2024/01.webp', '/images/events/samcheok-trek-2024/02.webp', '/images/events/samcheok-trek-2024/poster.webp'] },
    { order: 12, feat: false, year: 2024, title: '원주시 반려견 이동식 운동장',
      loc: '원주', ppl: '2,190', date: '2024 (7회 진행)',
      place: '강원특별자치도 원주시 일원', part: '자체 기획·제작·운영', organizer: '원주시·강원도반려동물협회',
      desc: '반려견이 마음껏 달릴 수 있도록. 원주 시내 7곳에서, 2,190명이 함께했습니다.',
      imageData: '/images/events/playground-2024/01.webp',
      imageData2: '/images/events/playground-2024/02.webp',
      images: ['/images/events/playground-2024/01.webp', '/images/events/playground-2024/02.webp'] },
    { order: 13, feat: false, year: 2023, title: '제1회 강릉시반려동물문화축제',
      loc: '강릉', ppl: '3,000', date: '2023.09.23(토)',
      place: '강원특별자치도 강릉시 경포호 일원', part: '자체 기획·제작·운영', organizer: '강릉시·강원도반려동물협회',
      desc: '강릉에서의 첫 만남. 경포호 일대가 반려동물 문화의 첫 페이지를 썼습니다.',
      imageData: '/images/events/gangwon-fest-2023/01.webp',
      imageData2: '/images/events/gangwon-fest-2023/02.webp',
      images: ['/images/events/gangwon-fest-2023/01.webp', '/images/events/gangwon-fest-2023/02.webp', '/images/events/gangwon-fest-2023/03.webp', '/images/events/gangwon-fest-2023/04.webp'] },
    { order: 14, feat: false, year: 2022, title: '전국댕댕자랑 사진공모전',
      loc: '원주', ppl: '1,340', date: '2022.11.22(월) ~ 12.06(화)',
      place: '강원특별자치도 원주시 (온·오프라인)', part: '자체 기획·제작·운영', organizer: '강원도반려동물협회',
      desc: '전국에서 모인 1,340개의 순간들. 우리 반려동물의 가장 빛나는 표정이 모였습니다.',
      imageData: '/images/events/photo-contest-2022/04.webp',
      imageData2: '/images/events/photo-contest-2022/05.webp',
      images: ['/images/events/photo-contest-2022/04.webp', '/images/events/photo-contest-2022/05.webp', '/images/events/photo-contest-2022/01.webp', '/images/events/photo-contest-2022/02.webp', '/images/events/photo-contest-2022/poster.webp'] },
    { order: 15, feat: false, year: 2021, title: '제1회 강원도반려동물문화축제',
      loc: '원주', ppl: '1,500', date: '2021 — 협회 창립',
      place: '강원특별자치도 원주시', part: '자체 기획·제작·운영', organizer: '강원도반려동물협회',
      desc: '협회가 시작됐고, 강원도가 달라졌습니다. 1,500명과 함께 쓴 첫 번째 장.',
      imageData: '/images/events/gangwon-fest-2021/02.webp',
      imageData2: '/images/events/gangwon-fest-2021/03.webp',
      images: ['/images/events/gangwon-fest-2021/02.webp', '/images/events/gangwon-fest-2021/03.webp', '/images/events/gangwon-fest-2021/new_05.webp', '/images/events/gangwon-fest-2021/new_06.webp', '/images/events/gangwon-fest-2021/new_04.webp', '/images/events/gangwon-fest-2021/new_09.webp', '/images/events/gangwon-fest-2021/new_10.webp', '/images/events/gangwon-fest-2021/new_11.webp', '/images/events/gangwon-fest-2021/01.webp'] },
  ],
  [STORES.PLACES]: [
    // ── 춘천 ──────────────────────────────────────────────
    { order: 1,  region: '춘천', type: '체험', typeLabel: '테마파크', name: '강아지숲', icon: '🌲',
      address: '춘천시 남산면 충효로 437',
      feature: '국내 최대 반려견 테마파크 · 리드줄 해제 운동장',
      desc: '3만 평 자연 숲 속 반려견 테마파크. 대·소형견 분리 운동장, 노즈워크 산책로, 어질리티 체험, 반려견 수영장 완비.',
      petInfo: '🐾 5차 예방접종 완료견 · 3개월 이상 · 맹견 입장 불가 · 리드줄 필수',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/강아지숲+춘천',
      hours: '10:00–18:00 (월요일·설·추석 당일 휴무)', price: '성인 17,000원 / 청소년 15,000원 / 어린이 12,000원 / 반려견 8,000원' },

    { order: 2,  region: '춘천', type: '체험', typeLabel: '레일바이크', name: '경강레일바이크 (강촌레일파크)', icon: '🚂',
      address: '춘천시 남산면 강촌로 1-1',
      feature: '반려견 전용 펫바이크 운영 · 북한강 철교 코스',
      desc: '경강역 폐역에서 출발해 북한강 철교를 건너는 코스. 반려견 전용 탑승석 펫바이크 별도 운영. 반려견 2마리까지 동반 탑승 가능.',
      petInfo: '🐾 펫바이크: 반려견 합산 10kg 이하 · 목줄 착용',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/경강레일바이크+강촌',
      hours: '09:00–17:40 (연중무휴)', price: '일반 2인승 20,000원 / 4인승 30,000원 (펫바이크 별도 문의)' },

    { order: 3,  region: '춘천', type: '체험', typeLabel: '카누·카약', name: '춘천 물레길 카누', icon: '🛶',
      address: '춘천시 스포츠타운길223번길 95 (의암호)',
      feature: '반려견과 카누 동승 · 의암호 수상 투어',
      desc: '의암호 위에서 반려견과 함께 즐기는 카누 체험. 자연생태공원길 코스(약 3km, 1시간) 인기. 중형견 이하 동반 탑승 가능.',
      petInfo: '🐾 중형견 이하 동반 가능 · 구명조끼 착용 필수',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/춘천물레길+의암호',
      hours: '10:00–19:00 (계절별 상이)', price: '2인 30,000원 (추가 성인 10,000원)' },

    { order: 4,  region: '춘천', type: '공원', typeLabel: '산책', name: '공지천 반려견 산책로', icon: '🌿',
      address: '춘천시 근화동 공지천 일대',
      feature: '넓은 강변 · 무료 개방',
      desc: '춘천 시내 한가운데 위치한 공지천변 산책로. 소형견부터 대형견까지 자유롭게 산책할 수 있는 강변 공원. 벤치와 쉼터 완비.',
      petInfo: '🐾 목줄 착용 필수 · 배변봉투 지참',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/공지천유원지+춘천',
      hours: '24시간 개방', price: '무료' },

    { order: 5,  region: '춘천', type: '관광', typeLabel: '케이블카', name: '삼악산 호수 케이블카', icon: '🚡',
      address: '춘천시 서면 박사로 473',
      feature: '소양강 호수 위 케이블카 · 반려동물 전용 캐빈',
      desc: '소양강 호수 수면 위를 가로지르는 케이블카. 반려동물 전용 캐빈 별도 운영으로 케이지 또는 이동가방에 넣은 반려동물 동반 탑승 가능.',
      petInfo: '🐾 소형 반려동물 · 케이지 또는 이동가방 필수',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/삼악산호수케이블카+춘천',
      hours: '09:00–18:00 (연중무휴)', price: '왕복 성인 14,000원 / 소인 11,000원' },

    // ── 강릉 ──────────────────────────────────────────────
    { order: 6,  region: '강릉', type: '호텔', typeLabel: '호텔', name: '세인트존스호텔', icon: '🏨',
      address: '강릉시 강문동 34-2',
      feature: '5성급 · 메이트쉽 파트너 최저가 보장 · 체중 제한 없음',
      desc: '경포 해변 바로 앞 5성급 호텔. 반려견 전용 객실 운영. 체중 제한 없이 최대 2마리 동반 가능. 반려견 전용 어메니티 제공.',
      petInfo: '🐾 전 견종 체중 제한 없음 · 최대 2마리(스위트 3마리)',
      isPartner: true, imageData: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/세인트존스호텔+강릉',
      hours: '체크인 15:00 / 체크아웃 11:00', price: '펫 객실 350,000원~ / 반려견 추가 30,000원' },

    { order: 7,  region: '강릉', type: '카페', typeLabel: '애견카페', name: '체크이스트 카페', icon: '☕',
      address: '강릉시 강변복길 153',
      feature: '사천해변 근처 감성 인테리어 · 반려견 전용 간식',
      desc: '사천해변 근처 골목에 자리한 감성 애견동반 카페. 반려견 전용 간식과 물그릇 비치. 테라스에서 산책 후 쉬어가기 좋음.',
      petInfo: '🐾 전 견종 · 목줄 착용 필수 · 배변패드 비치',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/체크이스트카페+강릉',
      hours: '10:00–20:00 (연중무휴)', price: '음료 6,000원–12,000원' },

    { order: 8,  region: '강릉', type: '카페', typeLabel: '카페', name: '카페콥스', icon: '☕',
      address: '강릉시 초당순두부길 54',
      feature: '초당동 감성 카페 · 넓은 마당',
      desc: '강릉 초당동 인기 카페. 넓은 야외 마당에서 반려견과 함께 여유롭게 커피와 베이커리를 즐길 수 있음.',
      petInfo: '🐾 전 견종 · 야외 공간 자유 동반 · 목줄 착용',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/카페콥스+강릉',
      hours: '11:00–20:00 (화요일 휴무)', price: '음료 6,000원–10,000원' },

    { order: 9,  region: '강릉', type: '카페', typeLabel: '프라이빗 카페', name: '르꼬따쥬', icon: '🏡',
      address: '강릉시 한밭골길 50-11',
      feature: '100% 예약제 프라이빗 팜크닉 · 반려견 동반 옵션',
      desc: '관광농원을 개조한 100% 예약제 프라이빗 카페. 잔디밭에서 반려견과 함께 팜크닉을 즐길 수 있음.',
      petInfo: '🐾 전 견종 · 예약 시 반려동물 동반 옵션 선택 필수',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/르꼬따쥬+강릉',
      hours: '10:00–17:00 (예약제 운영)', price: '음료 포함 인당 15,000원~ / 반려견 10,000원' },

    { order: 10, region: '강릉', type: '식당', typeLabel: '레스토랑', name: '그릴웍스', icon: '🍖',
      address: '강릉시 사천면 한과마을길 553',
      feature: '전 견종 실내 동반 · 텍사스 바베큐',
      desc: '강릉 사천에 위치한 정통 텍사스 바베큐 레스토랑. 실내·야외 테라스 모두 소·중·대형견 동반 가능.',
      petInfo: '🐾 소·중·대형견 실내외 동반 · 맹견 제외',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/그릴웍스+강릉',
      hours: '11:00–20:00 (월·화 휴무)', price: '메뉴당 15,000원–35,000원' },

    { order: 11, region: '강릉', type: '체험', typeLabel: '레일바이크', name: '정동진 레일바이크', icon: '🚂',
      address: '강릉시 강동면 정동진리 36-1',
      feature: '동해 바다 절경 · 소형 반려견 동반',
      desc: '정동진역~모래시계공원 구간 동해 바다를 옆에 두고 달리는 레일바이크. 소형 반려동물(3kg 이하) 케이지에 넣어 동반 탑승 가능.',
      petInfo: '🐾 소형견 3kg 이하 · 이동장(켄넬) 필수',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/정동진레일바이크',
      hours: '08:30–16:40 (연중무휴)', price: '2인승 25,000원 / 4인승 35,000원' },

    { order: 12, region: '강릉', type: '관광', typeLabel: '미술관', name: '하슬라아트월드', icon: '🎨',
      address: '강릉시 강동면 율곡로 1441',
      feature: '야외 조각공원 전 견종 가능 · 바다 전망',
      desc: '동해가 내려다보이는 언덕 위 아트뮤지엄. 넓은 야외 조각공원에서 반려견 목줄 착용 후 자유롭게 관람 가능.',
      petInfo: '🐾 야외 조각공원 전 견종 · 목줄 착용 · 실내 안고 이동',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/하슬라아트월드+강릉',
      hours: '09:00–18:00 (연중무휴)', price: '성인 17,000원 / 청소년 13,000원 / 어린이 11,000원' },

    { order: 13, region: '강릉', type: '공원', typeLabel: '해변·산책', name: '안목해변 펫비치', icon: '🌊',
      address: '강릉시 견소동 안목해변',
      feature: '100m 펫비치 전용 구역 · 샤워시설 완비',
      desc: '강릉 안목해변 내 반려견 전용 펫비치 100m 구간. 펜스 설치, 배변봉투함·파라솔·샤워시설 완비.',
      petInfo: '🐾 목줄 착용 필수(비치 내 해제 가능) · 배변봉투 지참',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1560807707-8cc77767d783?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/안목해변+강릉',
      hours: '24시간 개방 (성수기 시간 제한 있음)', price: '무료' },

    { order: 14, region: '강릉', type: '트레킹', typeLabel: '트레킹', name: '바우길 1코스 선자령 풍차길', icon: '🏔️',
      address: '강릉시 성산면 대관령로 560 (대관령 양떼목장 옆)',
      feature: '평탄 능선길 · 사계절 반려견 추천 코스',
      desc: '해발 1,157m 선자령까지 이어지는 평탄한 능선길. 겨울 설원, 여름 초록 능선 모두 절경. 편도 약 4km.',
      petInfo: '🐾 목줄 착용 필수 · 배변봉투 지참 · 대형견 가능',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1469521669194-babb45599def?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/선자령+대관령',
      hours: '상시 개방', price: '무료' },

    // ── 속초 ──────────────────────────────────────────────
    { order: 15, region: '속초', type: '공원', typeLabel: '공원·산책', name: '설악해맞이공원', icon: '🌅',
      address: '속초시 동해대로 3664 (대포동)',
      feature: '동해 일출 명소 · 반려견 산책 인프라 우수',
      desc: '속초 3경 중 하나. 해맞이광장·연인의길·행복의길 등 테마별 산책로. 반려견 동반 산책 명소.',
      petInfo: '🐾 목줄 착용 필수 · 배변봉투 지참',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/설악해맞이공원+속초',
      hours: '24시간 개방', price: '무료' },

    { order: 16, region: '속초', type: '공원', typeLabel: '반려견 놀이터', name: '영랑호 반려견 놀이터', icon: '🐾',
      address: '속초시 영랑호반길 일대',
      feature: '소·대형 분리 운동장 · 어질리티 시설',
      desc: '속초 3경 영랑호 수변공원 끝자락 반려견 전용 놀이터. 소형견·대형견 구역 완전 분리, 어질리티 시설 완비.',
      petInfo: '🐾 소·대형견 구역 분리 · 입장 후 목줄 해제 가능',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/영랑호+반려견+속초',
      hours: '상시 개방', price: '무료' },

    { order: 17, region: '속초', type: '카페', typeLabel: '카페', name: '칠성조선소', icon: '⚓',
      address: '속초시 중앙로46번길 45',
      feature: '실제 조선소 개조 · 이색 뉴트로 공간',
      desc: '실제 조선소를 개조한 속초 대표 핫플레이스. 넓은 야외 공간에서 반려견 동반 가능. 청초호 뷰가 매력.',
      petInfo: '🐾 야외 공간 전 견종 · 목줄 착용 · 실내 소형견만',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/칠성조선소+속초',
      hours: '11:00–19:00 (라스트오더 18:30)', price: '음료 6,000원–12,000원' },

    { order: 18, region: '속초', type: '공원', typeLabel: '호수 산책', name: '청초호 수변공원', icon: '🌊',
      address: '속초시 청호동 청초호 일대',
      feature: '호수 데크 산책 · 속초 시내 전망',
      desc: '강과 바다를 잇는 속초 청초호. 호수 주변 데크길에서 반려견과 함께 설악산과 속초 시내 전망을 즐길 수 있음.',
      petInfo: '🐾 목줄 착용 필수',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/청초호수변공원+속초',
      hours: '24시간 개방', price: '무료' },

    // ── 양양 ──────────────────────────────────────────────
    { order: 19, region: '양양', type: '해변', typeLabel: '애견 전용 해변', name: '멍비치 (양양 지경리)', icon: '🌊',
      address: '양양군 현남면 지경리해수욕장',
      feature: '전국 유일 반려견 전용 해수욕장 · 7~8월 운영',
      desc: '반려견 없이는 입장 불가능한 국내 유일 반려견 전용 해수욕장. 목줄 해제 구역, 샤워장·드라이룸 완비.',
      petInfo: '🐾 반려견 필수 동반 · 접종 권장 · 목줄 해제 구역 운영',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/멍비치+양양',
      hours: '09:00–18:00 (7~8월 시즌 운영)', price: '견주 5,000원 / 소형견 5,000원 / 중형견 10,000원 / 대형견 15,000원' },

    { order: 20, region: '양양', type: '캠핑', typeLabel: '해변 캠핑', name: '죽도해변 야영장', icon: '⛺',
      address: '양양군 현남면 죽도해변길 80',
      feature: '메이트쉽 회원 30% 할인 · 해변 바로 앞',
      desc: '동해 해변에서 바로 캠핑할 수 있는 반려견 동반 야영장. 죽도해변 모래사장을 배경으로 반려견과 함께 캠핑.',
      petInfo: '🐾 전 견종 · 목줄 상시 착용 · 배변 처리 필수',
      isPartner: true, imageData: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/죽도해변야영장+양양',
      hours: '체크인 14:00 / 체크아웃 11:00', price: '1박 30,000원~ (메이트쉽 회원 21,000원~)' },

    { order: 21, region: '양양', type: '공원', typeLabel: '해변·산책', name: '인구해변', icon: '🏄',
      address: '양양군 현남면 인구항길 일대',
      feature: '서핑 메카 · 반려견 동반 핫플',
      desc: '양양 서핑의 메카이자 반려견 동반 여행지. 서퍼들과 반려견이 어우러지는 독특한 분위기. 주변에 반려견 동반 카페·식당 밀집.',
      petInfo: '🐾 목줄 착용 필수 · 성수기 일부 구역 제한',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/인구해변+양양',
      hours: '24시간 개방', price: '무료' },

    // ── 고성 ──────────────────────────────────────────────
    { order: 22, region: '고성', type: '트레킹', typeLabel: '트레킹', name: '건봉사 반려견 산책로', icon: '🏔️',
      address: '고성군 거진읍 건봉사로 723',
      feature: '천년 고찰 주변 청정 숲길 · 무료',
      desc: '신라시대 창건 천년 고찰 건봉사 주변 청정 자연 트레킹 코스. 왕복 약 5km. 계곡과 숲이 어우러진 반려견 추천 코스.',
      petInfo: '🐾 목줄 착용 필수 · 배변봉투 지참',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/건봉사+고성',
      hours: '07:00–18:00 (연중무휴)', price: '무료' },

    { order: 23, region: '고성', type: '공원', typeLabel: '해변·산책', name: '화진포 해수욕장', icon: '🌊',
      address: '고성군 거진읍 화진포길 135',
      feature: '최북단 청정 해변 · 반려견 동반',
      desc: '국내 최북단 청정 석호와 동해 바다가 맞닿는 화진포. 바다, 호수, 갯벌을 함께 즐길 수 있으며 반려견 동반 산책 가능.',
      petInfo: '🐾 목줄 착용 필수 · 성수기 일부 제한',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/화진포해수욕장+고성',
      hours: '상시 개방', price: '무료' },

    { order: 24, region: '고성', type: '캠핑', typeLabel: '오토캠핑', name: '송지호오토캠핑장', icon: '⛺',
      address: '고성군 죽왕면 동해대로 6021',
      feature: '공공캠핑장 · 반려견 동반 · 송지호 뷰',
      desc: '고성군 운영 공공 오토캠핑장. 천연기념물 송지호 옆에 위치. 반려견 동반 사이트 운영.',
      petInfo: '🐾 목줄 착용 필수 · 지정 사이트에서만 동반',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/송지호오토캠핑장+고성',
      hours: '체크인 14:00 / 체크아웃 11:00', price: '1박 20,000원–35,000원' },

    // ── 평창 ──────────────────────────────────────────────
    { order: 25, region: '평창', type: '관광', typeLabel: '목장', name: '대관령 하늘목장', icon: '🐄',
      address: '평창군 대관령면 횡계리 470-5',
      feature: '해발 1,080m · 반려견 입장료 5,000원',
      desc: '해발 1,080m 대관령 고원 목장. 반려견 동반 가능 구역 지정. 드넓은 초원에서 반려견과 함께 인생사진 촬영.',
      petInfo: '🐾 목줄 착용 필수 · 가축 구역 접근 금지',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/대관령하늘목장+평창',
      hours: '하절기(4~10월) 09:00–18:00 / 동절기(11~3월) 09:00–17:30', price: '대인 8,000원 / 소인 6,000원 / 반려견 5,000원' },

    { order: 26, region: '평창', type: '리조트', typeLabel: '리조트', name: '휘닉스파크 리조트', icon: '🎿',
      address: '평창군 봉평면 태기로 174',
      feature: '4계절 리조트 · 펫 전용 객실 · 워터파크',
      desc: '평창 사계절 종합 리조트. 스키·워터파크·루지·골프 등 다양한 액티비티. 반려견 전용 객실 어메니티 완비.',
      petInfo: '🐾 20kg 이하 · 최대 2마리 · 종합백신·광견병 접종 증명 필수',
      isPartner: true, imageData: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/휘닉스파크+평창',
      hours: '체크인 15:00 / 체크아웃 11:00', price: '펫 객실 1박 180,000원~ / 반려견 추가 20,000원' },

    { order: 27, region: '평창', type: '관광', typeLabel: '양떼목장', name: '대관령 양떼목장', icon: '🐑',
      address: '평창군 대관령면 대관령마루길 483-32',
      feature: '반려견 동반 산책 · 양 먹이주기 체험',
      desc: '드라마 촬영지로 유명한 대관령 양떼목장. 반려견 동반으로 넓은 초원 산책 가능. 단, 양 구역 접근 제한.',
      petInfo: '🐾 목줄 착용 필수 · 양 구역 접근 금지',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/대관령양떼목장+평창',
      hours: '09:00–17:30 (연중무휴)', price: '성인 5,000원 / 소인 4,000원' },

    // ── 홍천 ──────────────────────────────────────────────
    { order: 28, region: '홍천', type: '리조트', typeLabel: '리조트', name: '소노펫클럽&리조트 비발디파크', icon: '🐾',
      address: '홍천군 서면 한치골길 262',
      feature: '반려견 특화 리조트 · 전용 레스토랑·수영장',
      desc: '반려견 동반 테마 리조트. 반려동물 전문 셰프의 전용 레스토랑, 반려견 행동 상담 센터, 반려견 풀장 완비.',
      petInfo: '🐾 맹견·45kg 이상 제외 · 2년 내 종합백신·광견병 접종',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/소노펫클럽+비발디파크+홍천',
      hours: '체크인 15:00 / 체크아웃 11:00', price: '1박 200,000원~ / 반려견 소중형 30,000원·대형 50,000원' },

    { order: 29, region: '홍천', type: '캠핑', typeLabel: '계곡 캠핑', name: '봉바위돌집 캠핑장', icon: '⛺',
      address: '홍천군 서면 반곡길 일대',
      feature: '계곡 뷰 명소 · 대형견 불가',
      desc: '홍천 계곡 뷰가 아름다운 캠핑장. 반려견 동반 가능하며 조용하고 프라이빗한 분위기.',
      petInfo: '🐾 최대 2마리 · 소·중형견만 (대형견 불가) · 목줄 착용 필수',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/봉바위돌집캠핑장+홍천',
      hours: '체크인 14:00 / 체크아웃 11:00', price: '1박 50,000원~' },

    { order: 30, region: '홍천', type: '공원', typeLabel: '산책', name: '횡성호수길 5구간', icon: '🌿',
      address: '횡성군 갑천면 횡성호수길 일대',
      feature: '호수 옆 흙길 · 관절 부담 없는 평지 코스',
      desc: '횡성호수를 끼고 걷는 약 10km 산책 코스. 흙길로 반려견 관절에 부담 없음. 사계절 산책 명소.',
      petInfo: '🐾 목줄 착용 필수 · 배변봉투 지참',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/횡성호수길',
      hours: '상시 개방', price: '무료' },

    // ── 원주 ──────────────────────────────────────────────
    { order: 31, region: '원주', type: '트레킹', typeLabel: '트레킹', name: '치악산 둘레길 11코스', icon: '🏔️',
      address: '원주시 소초면 치악로 일대',
      feature: '반려견 허용 국립공원 코스 · 야자매트 완비',
      desc: '치악산 국립공원 내 반려견 허용 구간. 야자매트 포장되어 반려견 관절 보호. 왕복 약 6km.',
      petInfo: '🐾 목줄 착용 필수 · 배변봉투 지참 · 동물등록증 권장',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1469521669194-babb45599def?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/치악산둘레길+원주',
      hours: '일출~일몰 (계절별 상이)', price: '무료' },

    { order: 32, region: '원주', type: '펜션', typeLabel: '애견펜션', name: '트리몰리 애견펜션', icon: '🏡',
      address: '원주시 귀래면 일대',
      feature: '견종 제한 없음 · 24시간 미온수풀 무료',
      desc: '견종 제한 없이 최대 4마리까지 동반 가능한 프라이빗 펜션. 개별 실내 미온수풀·바베큐장·운동장 제공.',
      petInfo: '🐾 전 견종 · 최대 4마리',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/트리몰리애견펜션+원주',
      hours: '체크인 15:00 / 체크아웃 11:00', price: '객실 59,000원~ / 반려견 15,000원/마리' },

    { order: 33, region: '원주', type: '공원', typeLabel: '산책', name: '원주 섬강 반려견 산책로', icon: '🌊',
      address: '원주시 섬강변 일대 (문막읍)',
      feature: '무료 · 강변 흙길 왕복 4km',
      desc: '섬강변을 따라 조성된 반려견 산책 코스. 왕복 약 4km. 자연 흙길로 반려견이 자연스럽게 즐길 수 있음.',
      petInfo: '🐾 목줄 착용 필수',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/섬강+원주',
      hours: '24시간 개방', price: '무료' },

    { order: 34, region: '원주', type: '식당', typeLabel: '레스토랑', name: '원주 무튼', icon: '🍽️',
      address: '횡성군 서원면 경강로 1428 (오크밸리 인근)',
      feature: '미슐랭 경력 쉐프 · 야외 테라스 전 견종',
      desc: '미슐랭 경력 쉐프가 운영하는 오크밸리 인근 레스토랑. 야외 테라스에서 소·중·대형견 동반 가능.',
      petInfo: '🐾 전 견종 야외 테라스 동반 · 실내 소형견만',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/무튼+오크밸리+횡성',
      hours: '11:00–21:00 (라스트오더 20:00, 수요일 휴무)', price: '메뉴당 20,000원–50,000원' },

    // ── 인제 ──────────────────────────────────────────────
    { order: 35, region: '인제', type: '체험', typeLabel: '래프팅', name: '내린천 반려견 래프팅', icon: '🌊',
      address: '인제군 기린면 내린천로 2011',
      feature: '메이트쉽 회원 할인 · 강원도 청정 래프팅',
      desc: '강원도 대표 래프팅 성지 내린천에서 반려견과 함께 래프팅 체험. 반려견 안전 조끼 대여 제공. 4월~10월 운영.',
      petInfo: '🐾 중형견 이하 · 반려견 안전 조끼 착용 필수',
      isPartner: true, imageData: 'https://images.unsplash.com/photo-1525973132219-88a8f0ec4fc7?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/내린천래프팅+인제',
      hours: '09:00–17:00 (4월~10월 운영)', price: '1인 35,000원~ (메이트쉽 회원 할인)' },

    { order: 36, region: '인제', type: '캠핑', typeLabel: '캠핑', name: '설하관광농원 캠핑장', icon: '⛺',
      address: '인제군 북면 설악로 3208',
      feature: '반려견 전용 울타리 사이트 · 목줄 해제 가능',
      desc: '설악산 입구 인근 자연 속 캠핑장. 반려동물 동반 전용 사이트에 울타리 설치로 목줄 해제 캠핑 가능.',
      petInfo: '🐾 20kg 이하 (대형견·맹견 불가) · 전용 사이트 배정',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/설하관광농원+인제',
      hours: '체크인 14:00 / 체크아웃 11:00', price: '1박 40,000원–60,000원' },

    { order: 37, region: '인제', type: '공원', typeLabel: '트레킹', name: '미산계곡 반려견 산책로', icon: '🏔️',
      address: '인제군 기린면 미산리 일대',
      feature: '청정 계곡 · 여름 반려견 물놀이 명소',
      desc: '인제 청정 미산계곡. 맑고 시원한 계곡물에서 반려견과 함께 물놀이 가능. 여름 피서지로 인기.',
      petInfo: '🐾 목줄 착용 필수 · 배변봉투 지참',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/미산계곡+인제',
      hours: '상시 개방', price: '무료' },

    // ── 화천 ──────────────────────────────────────────────
    { order: 38, region: '화천', type: '캠핑', typeLabel: '국립야영장', name: '국립화천숲속야영장', icon: '🌲',
      address: '화천군 하남면 용암리 일대',
      feature: '반려견 동반 가능 국립야영장 · 울타리·야자매트 완비',
      desc: '산림청 운영 반려견 동반 가능 국립자연휴양림 야영장. 강원도 유일. 전용 울타리·야자매트 설치 사이트.',
      petInfo: '🐾 동물등록 완료 · 광견병 예방접종 · 최대 2마리',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1567889977869-46d61e52ddfc?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/화천숲속야영장',
      hours: '체크인 14:00 / 체크아웃 11:00', price: '1박 10,000원–20,000원' },

    { order: 39, region: '화천', type: '공원', typeLabel: '산책·공원', name: '화천천 수달래 산책로', icon: '🌿',
      address: '화천군 화천읍 화천천 일대',
      feature: '무료 · 봄 수달래 군락 · 조용한 산책',
      desc: '화천천변을 따라 조성된 산책로. 봄에는 수달래(산철쭉) 군락이 아름답게 피어남. 반려견과 여유로운 산책에 적합.',
      petInfo: '🐾 목줄 착용 필수',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/화천천+화천',
      hours: '24시간 개방', price: '무료' },

    // ── 양구 ──────────────────────────────────────────────
    { order: 40, region: '양구', type: '공원', typeLabel: '생태공원', name: '한반도섬 (양구 수입천)', icon: '🌿',
      address: '양구군 방산면 수입리 한반도섬',
      feature: '국내 최대 인공 습지 · 반려견 데크 산책',
      desc: '위에서 보면 한반도 모양인 국내 최대 인공 습지섬. 잘 정비된 데크 산책로를 따라 반려견과 함께 생태 탐방 가능.',
      petInfo: '🐾 목줄 착용 필수 · 배변봉투 지참',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/한반도섬+양구',
      hours: '상시 개방', price: '무료' },

    // ── 정선 ──────────────────────────────────────────────
    { order: 41, region: '정선', type: '체험', typeLabel: '레일바이크', name: '정선 레일바이크', icon: '🚂',
      address: '정선군 여량면 레일바이크길 230',
      feature: '구절리~아우라지 7.2km · 소형 반려동물 동반',
      desc: '구절리역~아우라지 구간 약 7.2km 동강 절경을 따라 달리는 레일바이크. 소형 반려동물을 케이지에 넣어 동반 탑승 가능.',
      petInfo: '🐾 소형 반려동물 · 케이지(켄넬) 필수',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/정선레일바이크',
      hours: '09:00–17:30 (연중무휴)', price: '2인승 35,000원 / 4인승 50,000원' },

    { order: 42, region: '정선', type: '관광', typeLabel: '트레킹', name: '만항재 야생화 트레킹', icon: '🌸',
      address: '정선군 고한읍 함백산 만항재',
      feature: '해발 1,330m · 야생화 군락 · 반려견 트레킹',
      desc: '국내 포장도로 중 가장 높은 고개 만항재(해발 1,330m). 7~8월 야생화 군락이 장관. 반려견과 함께 쿨한 여름 고산 트레킹 가능.',
      petInfo: '🐾 목줄 착용 필수 · 추위 대비 필요',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1469521669194-babb45599def?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/만항재+정선',
      hours: '상시 개방', price: '무료' },

    // ── 삼척 ──────────────────────────────────────────────
    { order: 43, region: '삼척', type: '관광', typeLabel: '케이블카', name: '삼척 해상 케이블카', icon: '🚡',
      address: '삼척시 정상동 이사부길 33',
      feature: '동해 바다 위 케이블카 · 케이지 대여 가능',
      desc: '동양 최장 해상 케이블카 구간(1.4km). 소형 반려동물 케이지에 넣어 탑승 가능. 케이지 대여 서비스 제공.',
      petInfo: '🐾 소형 반려동물 케이지 탑승 · 케이지 대여 2,000원',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/삼척해상케이블카',
      hours: '09:00–18:00 (연중무휴)', price: '왕복 성인 12,000원 / 소인 8,000원 (케이지 대여 2,000원)' },

    { order: 44, region: '삼척', type: '공원', typeLabel: '해변·산책', name: '삼척 맹방해변', icon: '🌊',
      address: '삼척시 근덕면 맹방해변길 일대',
      feature: '넓은 백사장 · 반려견 동반 해변 산책',
      desc: '삼척의 넓고 깨끗한 백사장 맹방해변. 비교적 한적해 반려견과 함께 자유롭게 산책하기 좋음.',
      petInfo: '🐾 목줄 착용 필수 · 성수기 일부 제한',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/맹방해변+삼척',
      hours: '상시 개방', price: '무료' },

    // ── 동해 ──────────────────────────────────────────────
    { order: 45, region: '동해', type: '공원', typeLabel: '해변·공원', name: '묵호 논골담길 & 해변', icon: '🎨',
      address: '동해시 묵호동 논골담길 일대',
      feature: '벽화마을 · 바다 전망 · 반려견 산책',
      desc: '아름다운 벽화가 가득한 묵호 논골담길. 오르막 골목길을 반려견과 함께 걸으며 동해 바다 전망 감상.',
      petInfo: '🐾 목줄 착용 필수',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/묵호논골담길+동해',
      hours: '상시 개방', price: '무료' },

    // ── 태백 ──────────────────────────────────────────────
    { order: 46, region: '태백', type: '트레킹', typeLabel: '트레킹', name: '태백산 반려견 등반 코스', icon: '🏔️',
      address: '태백시 소도동 태백산국립공원',
      feature: '해발 1,567m 천제단 · 반려견 동반 허용 구간',
      desc: '태백산국립공원 내 반려견 동반 허용 구간. 유일사 탐방로 이용. 겨울 설경이 특히 아름다움.',
      petInfo: '🐾 동물등록 완료 · 목줄 착용 필수 · 허용 구간 외 출입 금지',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1469521669194-babb45599def?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/태백산국립공원',
      hours: '일출~일몰 (계절별 상이)', price: '성인 2,000원 / 소인 1,000원' },

    // ── 영월 ──────────────────────────────────────────────
    { order: 47, region: '영월', type: '관광', typeLabel: '동물원', name: '달빛동물원 (펫힐링)', icon: '🦜',
      address: '영월군 영월읍 단종로 산 9-2',
      feature: '반려동물 동반 입장 · 이색 동물 체험',
      desc: '다양한 이색 동물을 만날 수 있는 영월 달빛동물원. 반려견 동반 입장 가능하며 야간 운영으로 특별한 분위기.',
      petInfo: '🐾 반려견 동반 가능 · 목줄 착용 필수 · 공격성 견종 제한',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/달빛동물원+영월',
      hours: '10:00–22:00 (계절별 상이)', price: '성인 10,000원 / 소인 8,000원' },

    { order: 48, region: '영월', type: '공원', typeLabel: '산책', name: '영월 동강 래프팅 & 산책', icon: '🌊',
      address: '영월군 영월읍 동강 일대',
      feature: '동강 절경 · 반려견 강변 산책',
      desc: '영월 동강의 아름다운 절경을 따라 반려견과 함께 강변 산책 가능. 래프팅 시즌(5~9월) 수상 레저 체험도 가능.',
      petInfo: '🐾 목줄 착용 필수 · 래프팅 동반 시 운영사 사전 확인',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1525973132219-88a8f0ec4fc7?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/동강+영월',
      hours: '상시 개방', price: '무료 (래프팅 별도 요금)' },

    // ── 강릉 추가 ──────────────────────────────────────────
    { order: 49, region: '강릉', type: '식당', typeLabel: '맛집', name: '세레니타', icon: '🍝',
      address: '강릉시 율곡로 3034',
      feature: '전 견종 동반 · 이탈리안 다이닝',
      desc: '강릉 인기 이탈리안 레스토랑. 넓은 공간에서 소·중·대형견 동반 가능. 맹견 및 공격성 강한 견종 제외.',
      petInfo: '🐾 전 견종 동반 · 맹견 제외 · 목줄 착용',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/세레니타+강릉',
      hours: '11:30–21:00 (월요일 휴무)', price: '메뉴당 15,000원–30,000원' },

    { order: 50, region: '강릉', type: '공원', typeLabel: '해변', name: '사근진해변', icon: '🌊',
      address: '강릉시 해안로604번길 16 (사근진)',
      feature: '조용한 소규모 해변 · 전 견종 동반',
      desc: '강릉 북쪽의 작고 조용한 해변. 성수기에도 비교적 한적해 반려견과 여유롭게 시간을 보내기 좋음.',
      petInfo: '🐾 목줄 착용 필수 · 성수기 일부 시간 제한',
      isPartner: false, imageData: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
      mapUrl: 'https://map.naver.com/v5/search/사근진해변+강릉',
      hours: '24시간 개방', price: '무료' },
  ],
  [STORES.GALLERY]: [
    { order: 1, imageData: '/images/events/gosung-trek-2025/01.webp',  caption: '2025 Mission Dog Trekking — 고성', active: true },
    { order: 2, imageData: '/images/events/gapyeong-2025/01.webp',      caption: '가평군 반려동물 문화행사 — 활짝펫', active: true },
    { order: 3, imageData: '/images/events/beach-gosung-2025/02.webp',  caption: '고성 해변 반려견 축제 — 썬베드비치', active: true },
    { order: 4, imageData: '/images/events/wonju-2025/01.webp',        caption: '제3회 원주시 반려동물문화축제 — 애니멀대학교', active: true },
    { order: 5, imageData: '/images/events/wonju-2024/01.webp',        caption: '제2회 원주시 반려동물문화행사', active: true },
    { order: 6, imageData: '/images/gallery/ig_04.webp',               caption: '원주 반려동물 문화행사 현장', active: true },
    { order: 7, imageData: '/images/gallery/ig_06.webp',               caption: '고성 반려견 힐링 트레킹', active: true },
    { order: 8, imageData: '/images/gallery/ig_01.webp',               caption: '산책교육 현장 — 햅삐크루', active: true },
    { order: 9, imageData: '/images/gallery/ig_02.webp',               caption: '2026 청주시 반려동물 문화행사 — 학교종이 댕댕댕', active: true },
    { order: 10, imageData: '/images/gallery/ig_03.webp',              caption: '강원특별자치도 동물복지 정책 발표회', active: true },
  ],
  [STORES.MATESHIP]: [
    { order: 1, name: '세인트존스호텔',         region: '강릉', type: '호텔',     discount: '인터넷 최저가 이하', icon: '🏨',  gradient: 'linear-gradient(135deg,#dbeafe 0%,#93c5fd 100%)', link: '#', imageData: null },
    { order: 2, name: '피닉스파크 리조트',      region: '평창', type: '리조트',   discount: '회원 할인',          icon: '⛷️',  gradient: 'linear-gradient(135deg,#cffafe 0%,#67e8f9 100%)', link: '#', imageData: null },
    { order: 3, name: '퍼피파크 애견카페',      region: '원주', type: '카페',     discount: '30% 할인',           icon: '☕',  gradient: 'linear-gradient(135deg,#fef3c7 0%,#fcd34d 100%)', link: '#', imageData: null },
    { order: 4, name: '죽도해변 반려견 캠핑장', region: '양양', type: '캠핑',     discount: '30% 할인',           icon: '🏕️', gradient: 'linear-gradient(135deg,#dcfce7 0%,#86efac 100%)', link: '#', imageData: null },
    { order: 5, name: '반려동물 테마파크',      region: '홍천', type: '공원',     discount: '회원 할인',          icon: '🌳',  gradient: 'linear-gradient(135deg,#d1fae5 0%,#6ee7b7 100%)', link: '#', imageData: null },
    { order: 6, name: '내린천 반려견 래프팅',   region: '인제', type: '액티비티', discount: '회원 할인',          icon: '🚣',  gradient: 'linear-gradient(135deg,#dbeafe 0%,#7dd3fc 100%)', link: '#', imageData: null },
  ],
};

export const DEFAULT_HASHTAGS = [
  { page: 'index',     tags: ['#반려동물동반여행', '#강원도반려동물', '#반려동물훈련', '#반려동물협회', '#강원도캠핑'] },
  { page: 'events',    tags: ['#반려동물동반행사', '#반려동물축제', '#반려동물캠핑', '#강원도반려동물', '#반려동물페스티벌'] },
  { page: 'travel',    tags: ['#강원도반려동물동반', '#반려동물동반카페', '#속초반려동물', '#강릉반려동물', '#반려동물동반숙소'] },
  { page: 'education', tags: ['#반려동물행동지도사', '#반려동물교육', '#반려동물훈련', '#어질리티교육', '#반려동물국가자격증'] },
  { page: 'mateship',  tags: ['#반려동물할인', '#고양이사료할인', '#반려묘사료할인', '#반려동물멤버십', '#강원도반려동물혜택'] },
  { page: 'about',     tags: ['#강원도반려동물협회', '#GWAA', '#반려동물협회', '#강원도반려인', '#반려동물문화'] },
];
